spring:
  resources:
    add-mappings : true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: admin
    configuration:
      maximum-pool : 30
  jpa:
    hibernate:
      default_schema: redis
      ddl-auto: create-drop
    generate-ddl : true
    open-in-view: false  # disable global request transactions
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  application:
    name: redis
logging:
  level.: debug
  logging:
    file=${java.io.tmpdir}/${spring.aplication.name}.log

server:
  error:
    whitelabel:
      enabled : false
  port: 8585